const socketEvents = {
  UPDATE_DELIVERY_ASSOCIATE_LOCATION: 'UPDATE_DELIVERY_ASSOCIATE_LOCATION',
  UPDATE_DELIVERY_ASSOCIATE_STATUS: 'UPDATE_DELIVERY_ASSOCIATE_STATUS',
  UPDATE_SHIPMENT_STATUS: 'UPDATE_SHIPMENT_STATUS',
  BROADCAST_SHIPMENT: 'BROADCAST_SHIPMENT',
};
